{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-core",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-core-2.5.0.jar",
          "url": "specmatic-core-2.5.0.jar",
          "size": 6610176,
          "sha512": "e4a5f7e2a346c9613e0b843a9e7cfd036241e33da11fa700f0ddde39e4d116665a60baa5e3465a6c4def5af51c8567362c57804e57f15dc25d48ddd58289d46d",
          "sha256": "c1af9a47f7221977467ce655486e3f6211dd71ea7b824885eff740d428d7a44b",
          "sha1": "f5f2a4b2220879cedf97c35f84ac27c279b85b1d",
          "md5": "595f7dce06522bae7e9ccf0d8b70e225"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.ezylang",
          "module": "EvalEx",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "io.cucumber",
          "module": "gherkin",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cors",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-double-receive",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-jackson",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit.ssh.apache",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.flipkart.zjsonpatch",
          "module": "zjsonpatch",
          "version": {
            "requires": "0.4.16"
          }
        },
        {
          "group": "io.swagger.parser.v3",
          "module": "swagger-parser",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "com.github.mifmif",
          "module": "generex",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "dk.brics",
          "module": "automaton",
          "version": {
            "requires": "1.12-1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-core-2.5.0.jar",
          "url": "specmatic-core-2.5.0.jar",
          "size": 6610176,
          "sha512": "e4a5f7e2a346c9613e0b843a9e7cfd036241e33da11fa700f0ddde39e4d116665a60baa5e3465a6c4def5af51c8567362c57804e57f15dc25d48ddd58289d46d",
          "sha256": "c1af9a47f7221977467ce655486e3f6211dd71ea7b824885eff740d428d7a44b",
          "sha1": "f5f2a4b2220879cedf97c35f84ac27c279b85b1d",
          "md5": "595f7dce06522bae7e9ccf0d8b70e225"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-core-2.5.0-javadoc.jar",
          "url": "specmatic-core-2.5.0-javadoc.jar",
          "size": 261,
          "sha512": "679049f85b42e92ddd1510de151f177cacc23e7dd40d6dfcdb4c7c81023754c6f26c537fd262bc8f941212400447e16c0b19e49617974ff660d10e0831be01bf",
          "sha256": "c6447235adfac29643ede5a252066be0a3fc1ad95216473b374ec6b5f0eb81a7",
          "sha1": "a87aef1f6caaa603d4434cda5b2bd93086cbcc5e",
          "md5": "c0435cef36a8463e12b39d63721a0d77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-core-2.5.0-sources.jar",
          "url": "specmatic-core-2.5.0-sources.jar",
          "size": 3843080,
          "sha512": "625c70674ae8757798d2f31e33d991547bb1226d3fcf0a186717dbe7652021d5e8c65e6de8b094ffaed469e4ca5a9280d708c639fdcce310cc17db55e7bb0424",
          "sha256": "cda51b0fb8d08b0530d74320b84a72c2a0b57f7dff0fe49bd905149e8f5efed7",
          "sha1": "bcab826522b0e8ba109cc3a8941cbca206387e08",
          "md5": "54b2bc03c3f4b7d1ca63d30b8f0c03b3"
        }
      ]
    }
  ]
}
