{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-kafka",
    "version": "0.26.1-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-kafka-0.26.1-TRIAL.jar",
          "url": "specmatic-kafka-0.26.1-TRIAL.jar",
          "size": 712305,
          "sha512": "e02cea43f60ff30118163053c217ad99de284fe015277feee59f2d7657a6f7b8584301ea7f616bb0beff6fc5efa59a98cb6254ccdb910d1f929b08de6663b183",
          "sha256": "d1ae850e28013f616ec1a506051f8837966b6651ed1416365c38248ca111639f",
          "sha1": "f1cebc2cc40bbcb2b3930169c7b912d9e24ffada",
          "md5": "cfd47c66cc611904050e3f2593fd97b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka_2.13",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-framework",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-test",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.asyncapi",
          "module": "asyncapi-core",
          "version": {
            "requires": "1.0.0-RC3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-core",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-jackson",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20231013"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-kafka-0.26.1-TRIAL.jar",
          "url": "specmatic-kafka-0.26.1-TRIAL.jar",
          "size": 712305,
          "sha512": "e02cea43f60ff30118163053c217ad99de284fe015277feee59f2d7657a6f7b8584301ea7f616bb0beff6fc5efa59a98cb6254ccdb910d1f929b08de6663b183",
          "sha256": "d1ae850e28013f616ec1a506051f8837966b6651ed1416365c38248ca111639f",
          "sha1": "f1cebc2cc40bbcb2b3930169c7b912d9e24ffada",
          "md5": "cfd47c66cc611904050e3f2593fd97b9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
