{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-core",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-core-2.6.0.jar",
          "url": "specmatic-core-2.6.0.jar",
          "size": 6608101,
          "sha512": "385c6bcca0de59d9ea235828d06b4d781086684631f4a5efd372bfae29820fd165a6668f151ba88cfcfe848cf97e535a0e8218fbc5aea8fc08aa694756ef466a",
          "sha256": "fcc800770afdf95b79b547d1cb9429c4895efa871db7ab92acab6056e0b14ceb",
          "sha1": "8c7dd3741d6270bb30ae204dd4c31fb0e4dcb207",
          "md5": "48a70bfddeb19a382dfa330f77111bac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.ezylang",
          "module": "EvalEx",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "io.cucumber",
          "module": "gherkin",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cors",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-double-receive",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-jackson",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit.ssh.apache",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.flipkart.zjsonpatch",
          "module": "zjsonpatch",
          "version": {
            "requires": "0.4.16"
          }
        },
        {
          "group": "io.swagger.parser.v3",
          "module": "swagger-parser",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "com.github.mifmif",
          "module": "generex",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "dk.brics",
          "module": "automaton",
          "version": {
            "requires": "1.12-1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-core-2.6.0.jar",
          "url": "specmatic-core-2.6.0.jar",
          "size": 6608101,
          "sha512": "385c6bcca0de59d9ea235828d06b4d781086684631f4a5efd372bfae29820fd165a6668f151ba88cfcfe848cf97e535a0e8218fbc5aea8fc08aa694756ef466a",
          "sha256": "fcc800770afdf95b79b547d1cb9429c4895efa871db7ab92acab6056e0b14ceb",
          "sha1": "8c7dd3741d6270bb30ae204dd4c31fb0e4dcb207",
          "md5": "48a70bfddeb19a382dfa330f77111bac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-core-2.6.0-javadoc.jar",
          "url": "specmatic-core-2.6.0-javadoc.jar",
          "size": 261,
          "sha512": "4c9eac03ad7b4f35f554abf8318ef17dfcb4b8dc20476614c2c3ffb261cfccb3bd66c0399a37bd92b91be8ccf52bac0341b8acf1eff5790b6e6336263a11eb03",
          "sha256": "fbebef971c69e693e47151c6402b250327797194f3eda389bc0786419e1d6f0e",
          "sha1": "046b74d833ff5a5635a39e1dc6afde198a5d3f8c",
          "md5": "f5bf17defeecfaed59cf2db2039b94c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-core-2.6.0-sources.jar",
          "url": "specmatic-core-2.6.0-sources.jar",
          "size": 3842902,
          "sha512": "6229025e70630dc9ce3d52ff83de39cdeaf53e8d04283706d31cd49b6f9075e40226551f56c3d09653073c89564565ceb0cd297f0d7f5a3caef5eb1059014a8c",
          "sha256": "4c9e0d5e9d39c2797a211923a65c6a451978510b671b644bf73be4be72d688ae",
          "sha1": "53d4a4e1e13ab4636f2a9fc0ec094e51a6f32099",
          "md5": "65db8356e32db7decd36b7086f587aa7"
        }
      ]
    }
  ]
}
